brendanheywood/moodle-mod_cpdlogbook

lib.php
cpdlogbook instances can now be deleted. This resolves #11
=> Add the cpdlogbook_delete_instance function

classes/form/edit_entry.php, classes/tables/entries_table.php, delete.php, edit.php, lang/en/cpdlogbook.php, view.php
This merge fixes the basic issues in #13. The security issue is not resolved.
This merge also tries to fix the broken 'insert' functionality.
=> Crud form merge issues

classes/tables/entries_table.php, db/install.xml, edit.php, lib.php, view.php
This should resolve #19 for Postgres databases.
=> Change all foreign keys from `{obj}` to `{objid}`.

classes/tables/entries_table.php, lang/en/cpdlogbook.php, view.php
Replace the html_writer with a rendered action_menu. The update and delete actions both have corresponding icons.
This resolves #17
=> Use action_menu to display the actions.

classes/tables/entries_table.php, view.php
The 'actions' column doesn't display if the table is being downloaded. Otherwise, the html of the menu is in the downloaded file.
This resolves #45
=> Add download capability to view.php table

edit.php, lang/en/cpdlogbook.php, view.php
The progress bar is made using Bootstrap classes and html_writer.
Both options are available now for comparison, but this may be changed.
=> Display the points as a simple ratio and a progress bar

classes/event/entry_created.php, classes/tables/entries_table.php, details.php, lang/en/cpdlogbook.php, version.php
Resolves #53.
`details.php` currently only shows the minimum, basic information about the entry using `html_writer::alist`.
=> Details page

classes/event/course_module_viewed.php, view.php
=> Create course_module_viewed event

classes/event/course_module_viewed.php, classes/event/entry_created.php, classes/event/entry_deleted.php, classes/event/entry_updated.php, classes/form/edit_entry.php, classes/output/progressbar.php, classes/output/renderer.php, classes/tables/entries_table.php, db/access.php, delete.php, details.php, edit.php, index.php, lang/en/cpdlogbook.php, lib.php, mod_form.php, version.php, view.php
Document all existing files using the PHPdoc check plugin on Moodle.
=> Phpdoc update

classes/form/edit_entry.php, details.php, edit.php
If `fromdetails` is true, the user is redirected back to details.php, otherwise they're sent to view.php
Resolves #69
=> Add `fromdetails` param to edit.php

classes/event/entry_viewed.php, details.php
=> Add entry_viewed event

classes/tables/entries_table.php, lang/en/cpdlogbook.php
The format is 'yyyy-mm-dd'. The time seems to be read correctly when opening the csv export in Excel and Google Sheets.
This resolves #67
=> Time column is exported in friendly format.

README.md
=> Add installation information to readme

classes/form/edit_entry.php, classes/tables/entries_table.php, db/install.xml, db/upgrade.php, details.php, edit.php, lang/en/cpdlogbook.php, version.php
Changed field 'time' and all references to 'completiondate' for clarity.
=> Rename time field and add other date-related fields. Issue #20.

pix/icon.svg
=> Create simple svg icon

db/install.xml, db/upgrade.php, version.php, view.php
Creates a new `cpdlogbook_periods` table.
The table stores an id, startdate, enddate, and a foreign key referencing a cpdlogbook instance.
The `cpdlogbook_entries` table has a new foreign key so that an entry can be linked to a period.
=> Periods table

classes/tables/periods_table.php, lang/en/cpdlogbook.php, lib.php, periods.php
Adds a simple page to display the periods for a cpdlogbook instance.
A period can be inserted using the 'Add' button. The period is from the current time to exactly one month later.
=> Periods page

classes/form/edit_period.php, classes/tables/periods_table.php, delete.php, editperiod.php, periods.php
Adds a form for editing periods, and adds a `delete` action to the table.
=> Edit periods

classes/persistent/period.php, edit.php, tests/periods_test.php, tests/simple_test.php
The helper function assumes that no overlaps are present among the periods.
=> Links an entry with a period given the completiondate

classes/form/edit_period.php, classes/persistent/period.php, editperiod.php, lang/en/cpdlogbook.php
When validating a period, it is invalid if there are overlapping periods.
=> Check for an overlap when validating the period

classes/persistent/period.php, lang/en/cpdlogbook.php, periods.php
=> Display a notification is there are any entries without a period.

classes/form/edit_entry.php, edit.php, lang/en/cpdlogbook.php
=> Don't allow entries that don't fall within a period.

classes/form/edit_period.php, classes/persistent/period.php, classes/tables/periods_table.php, db/install.xml, db/upgrade.php, editperiod.php, lang/en/cpdlogbook.php, version.php
=> Add points field to period

view.php
=> Fixed files showing in activity intro

classes/form/edit_entry.php, details.php, edit.php, lang/en/cpdlogbook.php, lib.php
=> Upload evidence

classes/tables/entries_table.php, classes/tables/periods_table.php
Resolves #102.
I'm not getting any error when sorting on the 'points' column for periods, so I've left that as is for now.
=> Disable sorting by actions.

classes/output/entrydetails.php, classes/output/renderer.php, details.php, templates/entrydetails.mustache
Resolves #107. A mustache template is used to display the data, including the attachements.
=> Add template for details page

README.md
=> Simple credits

classes/form/edit_entry.php, classes/output/entrydetails.php, db/install.xml, db/upgrade.php, details.php, edit.php, lang/en/cpdlogbook.php, lib.php, templates/entrydetails.mustache, version.php
Unfinished.
Doesn't do file uploads. Doesn't save value when editing entry.
Issue #80
=> Added reflection section in entries

templates/entrydetails.mustache
=> Improved entry details page

lang/en/cpdlogbook.php
=> Simple alphabetical ordering and separation of lang strings.

classes/output/progressbar.php, classes/persistent/period.php, editperiod.php, lang/en/cpdlogbook.php, templates/progressbar.mustache, view.php
=> Show a target percentage in the progress bar.

classes/form/edit_entry.php, details.php, edit.php, lang/en/cpdlogbook.php, lib.php, templates/entrydetails.mustache
=> Renamed "attachments" to "evidence"
